server {
    listen 8080;
    server_name _;

    root /var/www/portfolio-prototypes;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /public/ {
        alias /var/www/portfolio-public/;
    }
}
